@startuml ItemData

interface IBossPageState
{
    Boss boss;
    void Attack();
    void Move();
}

abstract class BossPageState
{
}

class BossPageStateOne
{

}

class BossPageStateTwo
{

}

class BossPageStateThree
{

}

Boss *-- IBossPageState
IBossPageState <|.. BossPageState
BossPageState <|-- BossPageStateOne
BossPageState <|-- BossPageStateTwo
BossPageState <|-- BossPageStateThree
IBossPageState <-- Boss

@enduml