@startuml test

interface Subject {
    +notify(Observer): void
}

class ConcreteSubject {
    +notify(Observer): void
}

interface Observer {
    +update(): void
}

class ConcreteObserverA {
    +update(): void
}

class ConcreteObserverB {
    +update(): void
}

class ConcreteObserverC {
    +update(): void
}

Subject --> Observer
Subject <|.. ConcreteSubject
Observer <|.. ConcreteObserverA
Observer <|.. ConcreteObserverB
Observer <|.. ConcreteObserverC
ConcreteSubject --> ConcreteObserverA
ConcreteSubject --> ConcreteObserverB
ConcreteSubject --> ConcreteObserverC

@enduml